default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: collage_development

test:
  <<: *default
  database: collage_test

production:
  adapter: postgresql
  database: collage_production
  username: postgres
  pool: 5
  timeout: 5000
